name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged
        ports:
          - 2181:2181
          - 9092:9092
          - 8080:8080
          - 8081:8081
          - 9042:9042
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Services
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Sleeping to allow services to become healthy..."
          sleep 60
          docker compose ps

      - name: Stop Docker Compose
        if: always()
        run: docker compose down

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flake8

      - name: Lint Airflow DAG
        run: flake8 dags/kafka_streams.py --max-line-length=100

